baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[module]
[[module.imports]]
    path = 'github.com/hugomods/decap-cms'
[outputs]
  home = ['HTML', 'RSS', 'DecapCMSConfig']
[params]
  [params.decap_cms]
    media_folder = 'static/images/uploads'
    public_folder = '/images/uploads'
    publish_mode = 'editorial_workflow'
    search = true
    [params.decap_cms.collections]
      [params.decap_cms.collections.blog]
        folder = 'content/blog'
        label = 'Blog'
        other = '...'
      [params.decap_cms.collections.docs]
        folder = 'content/docs'
        label = 'Docs'
        other = '...'